[functions.stripe-webhook]
entrypoint = "functions/stripe-webhook/index.ts"
import_map = "functions/import_map.json"

[functions.create-checkout-session]
entrypoint = "functions/create-checkout-session/index.ts"
import_map = "functions/import_map.json"